# Generated by Django 5.1.6 on 2025-02-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_options_alter_quote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='book_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='book_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
